<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jh_captcha"
 *
 * Auto generated by Extension Builder 2015-04-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Google reCAPTCHA v2.0',
	'description' => 'With this extension you can use reCAPTCHA v2.0 from Google in your own TYPO3 extensions as spam protection. Moreover, this extension can be easily used in powermail forms.',
	'category' => 'fe',
	'author' => 'Jan Haffner',
	'author_email' => 'info@jan-haffner.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.1.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-7.4.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);