<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jh_captcha"
 *
 * Auto generated by Extension Builder 2015-02-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Captcha Library',
	'description' => 'Library for Google reCaptcha',
	'category' => 'misc',
	'author' => 'Jan Haffner',
	'author_email' => 'info@jan-haffner.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);